package com.github.donnyk22.models.entities.mybatis.autogenerated;

import jakarta.annotation.Generated;
import java.time.LocalDateTime;

public class MstUsers {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3932215+07:00", comments="Source field: mst_users.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.username")
    private String username;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.email")
    private String email;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.password")
    private String password;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.role")
    private String role;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_enabled")
    private Boolean mfaEnabled;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_secret")
    private String mfaSecret;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.is_active")
    private Boolean isActive;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.deleted")
    private Boolean deleted;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.version")
    private Integer version;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.created_at")
    private LocalDateTime createdAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.updated_at")
    private LocalDateTime updatedAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.photo")
    private String photo;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3942008+07:00", comments="Source field: mst_users.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3942008+07:00", comments="Source field: mst_users.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.username")
    public String getUsername() {
        return username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.username")
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.email")
    public String getEmail() {
        return email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.email")
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.password")
    public String getPassword() {
        return password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3951913+07:00", comments="Source field: mst_users.password")
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.role")
    public String getRole() {
        return role;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.role")
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_enabled")
    public Boolean getMfaEnabled() {
        return mfaEnabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_enabled")
    public void setMfaEnabled(Boolean mfaEnabled) {
        this.mfaEnabled = mfaEnabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_secret")
    public String getMfaSecret() {
        return mfaSecret;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.mfa_secret")
    public void setMfaSecret(String mfaSecret) {
        this.mfaSecret = mfaSecret == null ? null : mfaSecret.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.is_active")
    public Boolean getIsActive() {
        return isActive;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.is_active")
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3966981+07:00", comments="Source field: mst_users.deleted")
    public Boolean getDeleted() {
        return deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.deleted")
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.version")
    public Integer getVersion() {
        return version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.version")
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.created_at")
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.created_at")
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.updated_at")
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.updated_at")
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.photo")
    public String getPhoto() {
        return photo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.3977053+07:00", comments="Source field: mst_users.photo")
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }
}