package com.github.donnyk22.repositories.mybatis.autogenerated;

import com.github.donnyk22.models.entities.mybatis.autogenerated.MstUsers;
import com.github.donnyk22.models.entities.mybatis.autogenerated.MstUsersExample;
import jakarta.annotation.Generated;
import java.util.List;

public interface MstUsersMapper {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4027175+07:00", comments="Source Table: mst_users")
    long countByExample(MstUsersExample example);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4057145+07:00", comments="Source Table: mst_users")
    int deleteByPrimaryKey(Integer id);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4067178+07:00", comments="Source Table: mst_users")
    int insert(MstUsers row);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.407225+07:00", comments="Source Table: mst_users")
    int insertSelective(MstUsers row);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4082341+07:00", comments="Source Table: mst_users")
    List<MstUsers> selectByExampleWithBLOBs(MstUsersExample example);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4082341+07:00", comments="Source Table: mst_users")
    List<MstUsers> selectByExample(MstUsersExample example);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4092327+07:00", comments="Source Table: mst_users")
    MstUsers selectByPrimaryKey(Integer id);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4102303+07:00", comments="Source Table: mst_users")
    int updateByPrimaryKeySelective(MstUsers row);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4112302+07:00", comments="Source Table: mst_users")
    int updateByPrimaryKeyWithBLOBs(MstUsers row);

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-06-08T12:40:56.4112302+07:00", comments="Source Table: mst_users")
    int updateByPrimaryKey(MstUsers row);
}